import Link from "next/link";
import { ArrowRight,BadgeCheck,Building2,CheckCircle2,ShieldCheck,ShoppingBag,WalletCards } from "lucide-react";

export default function Home(){return <main className="landing-shell">
  <nav className="landing-nav"><div className="brand-lockup"><span className="brand-mark">G</span><span>GearGuard</span></div><div className="nav-actions"><Link href="/login" className="text-link">Sign in</Link><Link href="/portal" className="button button-dark">Open portal <ArrowRight size={16}/></Link></div></nav>
  <section className="hero-grid"><div><div className="eyebrow"><ShieldCheck size={15}/> Built for public safety procurement</div><h1>Uniform allowances that finally run like a system.</h1><p className="hero-copy">Connect a Shopify B2B company, synchronize every member and product, assign allowances, automate approvals, and keep every dollar visible from request to fulfillment.</p><div className="hero-actions"><Link href="/portal" className="button button-red">View live portal <ArrowRight size={17}/></Link><a href="#workflow" className="button button-light">See how it works</a></div><div className="trust-row"><span><CheckCircle2 size={16}/> Shopify B2B native</span><span><CheckCircle2 size={16}/> Audit-ready ledger</span><span><CheckCircle2 size={16}/> Member self-service</span></div></div>
  <div className="hero-console"><div className="console-top"><div><span className="console-kicker">Metro Fire & Rescue</span><strong>Department overview</strong></div><span className="live-dot">Live</span></div><div className="console-stats"><div><span>Active members</span><b>84</b></div><div><span>Available</span><b>$24,810</b></div><div><span>Pending</span><b className="amber">$1,294</b></div></div><div className="console-chart"><div className="chart-head"><span>Allowance utilization</span><b>68%</b></div><div className="bars">{[42,66,55,83,72,91,64,79].map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div></div><div className="console-order"><div className="order-icon"><ShoppingBag size={18}/></div><div><strong>GG-260904-8C2F</strong><span>Jordan Ellis · Job Shirt</span></div><b>$82.00</b><em>Approval</em></div></div></section>
  <section id="workflow" className="feature-strip"><article><Building2/><div><b>Import the company</b><p>Bring Shopify B2B contacts and locations into the correct department.</p></div></article><article><WalletCards/><div><b>Control allowances</b><p>Assign, reserve, reset, and audit individual balances without spreadsheets.</p></div></article><article><BadgeCheck/><div><b>Approve and fulfill</b><p>Route eligible orders to Shopify and keep status synchronized automatically.</p></div></article></section>
</main>}
