"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight,CheckCircle2,ShieldCheck } from "lucide-react";
import { createBrowserSupabase } from "@/lib/supabase/browser";

export function LoginForm({demo}:{demo:boolean}){
  const router=useRouter();
  const [method,setMethod]=useState<"pin"|"email">("pin");
  const [email,setEmail]=useState("");const [pin,setPin]=useState("");const [sent,setSent]=useState(false);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
  function changeMethod(next:"pin"|"email"){setMethod(next);setError("");setSent(false)}
  async function submitEmail(event:React.FormEvent){event.preventDefault();if(demo){router.push("/portal");return}setLoading(true);setError("");const supabase=createBrowserSupabase();const {error:authError}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/auth/confirm`}});setLoading(false);if(authError)setError(authError.message.toLowerCase().includes("rate limit")?"Email sign-in is temporarily busy. Use your PIN or try again later.":authError.message);else setSent(true)}
  async function submitPin(event:React.FormEvent){event.preventDefault();if(demo){router.push("/manager");return}setLoading(true);setError("");try{const response=await fetch("/api/auth/pin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pin})});const data=await response.json();if(!response.ok)throw new Error(data.error||"PIN sign-in failed");router.push(data.destination||"/portal");router.refresh()}catch(loginError){setError(loginError instanceof Error?loginError.message:"PIN sign-in failed")}finally{setLoading(false)}}
  return <div className="login-page"><section className="login-story"><Link href="/" className="brand-lockup"><span className="brand-mark">G</span><span>GearGuard</span></Link><div><span className="eyebrow"><ShieldCheck size={15}/> Secure agency access</span><h1>Every member. Every allowance. One clean ledger.</h1><p>GearGuard verifies members against your connected Shopify B2B company and gives each person the right portal automatically.</p><div className="login-points"><span><CheckCircle2/>Individual PIN or secure email access</span><span><CheckCircle2/>Manager permissions by department</span><span><CheckCircle2/>Financial changes are server controlled</span></div></div><small>Uniform procurement infrastructure for public safety.</small></section><section className="login-panel"><div className="login-card">{sent?<><div className="success-icon"><CheckCircle2/></div><h2>Check your inbox</h2><p>We sent a secure sign-in link to <b>{email}</b>.</p><button className="login-back" onClick={()=>changeMethod("pin")}>Use PIN instead</button></>:<><span className="mini-label">Member and manager portal</span><h2>Sign in to GearGuard</h2><div className="login-methods" role="tablist" aria-label="Sign-in method"><button type="button" className={method==="pin"?"active":""} onClick={()=>changeMethod("pin")}>PIN</button><button type="button" className={method==="email"?"active":""} onClick={()=>changeMethod("email")}>Email link</button></div>{method==="pin"?<><p>Enter the PIN assigned to your member account.</p><form onSubmit={submitPin}><label>Member PIN</label><input className="pin-input" type="password" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]*" minLength={4} maxLength={8} required value={pin} onChange={event=>setPin(event.target.value.replace(/\D/g,"").slice(0,8))} placeholder="••••"/>{error&&<div className="form-error">{error}</div>}<button className="button button-red" disabled={loading}>{loading?"Signing in…":"Sign in with PIN"}<ArrowRight size={17}/></button></form></>:<><p>Use the email address assigned to your department&apos;s Shopify company.</p><form onSubmit={submitEmail}><label>Email address</label><input type="email" required value={email} onChange={event=>setEmail(event.target.value)} placeholder="name@department.gov"/>{error&&<div className="form-error">{error}</div>}<button className="button button-red" disabled={loading}>{loading?"Sending…":"Send secure link"}<ArrowRight size={17}/></button></form></>}{demo&&<div className="demo-callout"><b>Preview mode</b><span>No account is required while the database is being connected.</span><Link href="/portal">Enter member portal →</Link><Link href="/manager">Enter manager portal →</Link></div>}</>}</div></section></div>
}
