import { apiFailure,ApiError,requireAppMember } from "@/lib/api-auth";
import { COMPANY_QUERY,inferCategory,PRODUCTS_QUERY,shopifyGraphQL,stripHtml } from "@/lib/shopify";

type CompanyContact={id:string;customer?:{id:string;firstName?:string;lastName?:string;defaultEmailAddress?:{emailAddress?:string};state:string};roleAssignments:{nodes:Array<{companyLocation?:{id:string}}>}};
type CompanyData={company:{id:string;name:string;locations:{nodes:Array<{id:string;name:string}>};contacts:{nodes:CompanyContact[]}}|null};
type ProductsPage={products:{nodes:ShopifyProduct[];pageInfo:{hasNextPage:boolean;endCursor:string|null}}};
type ShopifyProduct={id:string;title:string;handle:string;descriptionHtml:string;vendor:string;productType:string;tags:string[];status:string;featuredMedia?:{preview?:{image?:{url?:string}}};variants:{nodes:Array<{id:string;title:string;sku:string;price:string;inventoryQuantity:number;availableForSale:boolean;selectedOptions:Array<{name:string;value:string}>}>}};

export async function POST(){try{
  const {member,admin}=await requireAppMember(true);const departmentResult=await admin.from("departments").select("*").eq("id",member.department_id).single();if(departmentResult.error)throw departmentResult.error;const department=departmentResult.data;if(!department.shopify_company_id)throw new ApiError("Select a Shopify B2B company first");
  await admin.from("departments").update({shopify_sync_status:"SYNCING",shopify_sync_error:null}).eq("id",department.id);
  const companyData=await shopifyGraphQL<CompanyData>(COMPANY_QUERY,{id:department.shopify_company_id});if(!companyData.company)throw new ApiError("Shopify company was not found",404);let membersCreated=0,membersUpdated=0;
  for(const contact of companyData.company.contacts.nodes){const customer=contact.customer;const email=customer?.defaultEmailAddress?.emailAddress?.toLowerCase();if(!customer||!email)continue;const locationId=contact.roleAssignments.nodes.find(item=>item.companyLocation)?.companyLocation?.id||department.shopify_company_location_id||companyData.company.locations.nodes[0]?.id||null;let existing=await admin.from("members").select("*").eq("shopify_company_contact_id",contact.id).maybeSingle();if(!existing.data)existing=await admin.from("members").select("*").ilike("email",email).maybeSingle();const payload={department_id:department.id,email,first_name:customer.firstName||existing.data?.first_name||"Member",last_name:customer.lastName||existing.data?.last_name||"",status:customer.state==="DISABLED"?"inactive":"active",shopify_customer_id:customer.id,shopify_company_contact_id:contact.id,shopify_company_location_id:locationId,shopify_synced_at:new Date().toISOString()};if(existing.data){await admin.from("members").update(payload).eq("id",existing.data.id);membersUpdated++}else{const created=await admin.from("members").insert({...payload,role:"member"}).select().single();if(created.error)throw created.error;await admin.from("allowance_accounts").insert({department_id:department.id,member_id:created.data.id,annual_amount:department.default_annual_allowance||0,current_balance:0,reserved_amount:0,spent_amount:0,reset_date:department.allowance_reset_date});membersCreated++}}
  const products:ShopifyProduct[]=[];let after:string|null=null;do{const data:ProductsPage=await shopifyGraphQL<ProductsPage>(PRODUCTS_QUERY,{first:100,after,query:"status:active"});products.push(...data.products.nodes);after=data.products.pageInfo.hasNextPage?data.products.pageInfo.endCursor:null}while(after&&products.length<5000);
  for(const product of products){const variants=product.variants.nodes.map(variant=>({id:variant.id,title:variant.title,sku:variant.sku||"",price:Number(variant.price),inventory_quantity:variant.inventoryQuantity,available:variant.availableForSale,selected_options:variant.selectedOptions}));if(!variants.length)continue;const existing=await admin.from("products").select("*").eq("shopify_product_id",product.id).maybeSingle();const payload={title:product.title,description:stripHtml(product.descriptionHtml||""),category:existing.data?.category||inferCategory(product),image_url:product.featuredMedia?.preview?.image?.url||existing.data?.image_url||null,price:Math.min(...variants.map(item=>item.price)),allowance_eligible:existing.data?.allowance_eligible??true,approval_required:existing.data?.approval_required??false,active:product.status==="ACTIVE",shopify_product_id:product.id,shopify_handle:product.handle,shopify_vendor:product.vendor,shopify_product_type:product.productType,shopify_tags:product.tags,variants,shopify_synced_at:new Date().toISOString()};const result=existing.data?await admin.from("products").update(payload).eq("id",existing.data.id):await admin.from("products").insert(payload);if(result.error)throw result.error}
  const now=new Date().toISOString();await admin.from("departments").update({shopify_company_name:companyData.company.name,shopify_company_location_id:department.shopify_company_location_id||companyData.company.locations.nodes[0]?.id,shopify_shop_domain:process.env.SHOPIFY_SHOP_DOMAIN,shopify_sync_status:"CONNECTED",shopify_last_sync_at:now,shopify_sync_error:null}).eq("id",department.id);await admin.from("shopify_sync_runs").insert({department_id:department.id,status:"SUCCESS",members_created:membersCreated,members_updated:membersUpdated,products_synced:products.length,finished_at:now});return Response.json({success:true,members:{created:membersCreated,updated:membersUpdated},products:{synced:products.length},lastSync:now});
}catch(error){return apiFailure(error)}}
